[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies.prost]
version = "0.11"

[dependencies.prost-types]
version = "0.11"

[dependencies.tonic]
version = "0.9"

[dependencies.tokio]
version = "1"
features = [
	"rt-multi-thread",
]

[build-dependencies.tonic-build]
version = "0.9"

